Friendlyname
ambianic/ambianic-ui pull request #461
Opened 2020-12-04 20:20 UTC by BKristenssonAlfsson

Friendlyname showing in Navbar and dropdown in Settings

2020-12-07 20:30 UTC, ivelin requested changes
Good start, but UX needs some work. See screenshots below. It should be immediately clear to the user what the added value is of this PR.

- Navbar text goes past the navbar boundaries. It sometimes shows "connected to :" (blank, nothing). See images with different display form factors - responsive, mobile.
- As we are moving towards multiple edge device management, we need to reconsider the purpose of this navbar info. What do we want it to show when there are more than one connected devices?
- The settings screen now looks confusing. See screenshots. Remote device section is blank and it has a blank dropdown.
- We need unit tests added for this feature to document programmatically what it's intended purpose is.
- This branch needs to be merged with upstream master since its behind now. I did the merge locally without any issues.
- Please follow the commit lint guidelines to avoid the red flag. "feat: display edge friendly name."


![Screen Shot 2020-12-07 at 2 23 13 PM](https://user-images.githubusercontent.com/2234901/101401455-02515080-3898-11eb-823c-18160cecbff9.png)
![Screen Shot 2020-12-07 at 2 20 59 PM](https://user-images.githubusercontent.com/2234901/101401457-02e9e700-3898-11eb-9657-36f489d3faea.png)
![Screen Shot 2020-12-07 at 2 22 31 PM](https://user-images.githubusercontent.com/2234901/101401459-02e9e700-3898-11eb-8b25-d6e565374eb8.png)
![Screen Shot 2020-12-07 at 2 23 26 PM](https://user-images.githubusercontent.com/2234901/101401460-03827d80-3898-11eb-97e8-7c9c4689f09e.png)
![Screen Shot 2020-12-07 at 2 22 47 PM](https://user-images.githubusercontent.com/2234901/101401462-054c4100-3898-11eb-8cae-cb7ba231f1f4.png)
![Screen Shot 2020-12-07 at 2 23 08 PM](https://user-images.githubusercontent.com/2234901/101401463-054c4100-3898-11eb-813d-2baf23947e4d.png)

2021-01-04 22:07 UTC, ivelin requested changes
See a few comments inline.

2021-01-05 07:40 UTC, BKristenssonAlfsson commented on src/store/pnp.js
> +  [ADD_NEW_FRIENDLY_NAME] (state, edgeFriendlyName) {
Was said that this PR should only have it stored in an array so current session has the details. Subsequent PR would implement Localstorage. This to not generate to big PR.

2021-01-05 07:42 UTC, BKristenssonAlfsson commented on src/store/pnp.js
> +  [ADD_NEW_FRIENDLY_NAME] (state, edgeFriendlyName) {
Naming are up for debate. as it started with just adding in a friendlyname to a PeerID, I felt it was most appropiate to use that.

2021-01-05 07:45 UTC, BKristenssonAlfsson commented on src/store/pnp.js
> +      if (!state.peerFriendlyName.some(data => data.edgeFriendlyName === 'My Home Ambianic')) {
This was as a remote Edge has a name, but your own local Edge, this was decided in the poll a few months ago to have a default value for your own Edge.

The condition is that if I don't check if the device is already in the array, you can have same PeerID multiple times inserted in the array / localstorage.

This generated a bug that escalated, and in the end, it had to be resolved somehow. I did try resolve it in pnp.js too, with mediocre results when it actually could push it in even if it was stored.

2021-01-05 07:46 UTC, BKristenssonAlfsson commented on src/store/pnp.js
> +        state.peerFriendlyName.push(edgeFriendlyName)
Localstorage was decided to be a subsequent PR when I started this

2021-01-05 07:47 UTC, BKristenssonAlfsson commented on src/store/pnp.js
> +    commit(CURRENT_ACTIVE_USER, 'My Home Ambianic')
In the poll, it was voted to have the current active Edge friendlyname in the navbar. Hence the implementation

2021-01-23 20:24 UTC, BKristenssonAlfsson commented
Closed as the scope was drastically changed and became an epic

2021-01-23 20:24 UTC, closed without merging