feat: apply dynamic imports for all components
ambianic/ambianic-ui pull request #493
Opened 2021-01-23 16:45 UTC by sniperadmin

this should enhance the Lighthouse tests

2021-01-23 16:57 UTC, sniperadmin commented
@ivelin now it needs npm to be installed,
I am just confused as we have `yarn`
but anyways, I think this step could make some changes

2021-01-23 19:02 UTC, vickywane commented on package.json
> +    "webpack-bundle-analyzer": "^4.4.0"
You installed new dependencies here. 

Were new lock files generated and have you tried deleting the existing ones alongside your `node_modules`  then running a fresh installation with `npm install` ?

2021-01-23 19:06 UTC, vickywane reviewed
Your PR looks great. 
I think you should delete the lock files and `node_modules` then run fresh installations.

If package managers are a source of problems with the CI builds, then other contributors should be aware of the selected package manager.

2021-01-23 19:08 UTC, vickywane commented
Netlify checks seem to be breaking, have you had a look @sniperadmin ?

2021-01-23 19:10 UTC, sniperadmin commented
looks natural, coz npm was not able to get installed

2021-01-25 18:55 UTC, ivelin commented
@sniperadmin CI checks still fail. Converting this PR to draft until all checks are green.

2021-01-27 18:19 UTC, ivelin requested changes
There are a number of issues

1. The theme does not respond to the OS change to light/dark as it used to before #445
2. I don’t think we need a light/dark switch at the top menu. The app should respond to the OS settings. If we want to offer an explicit switch, we can put it in settings somewhere, but definitely not as a top navbar button.
3. The timeline view is broken. Nothing renders in the timeline page.

I think going forward we will need a lot more thorough test coverage for UI PRs to avoid regression.

2021-03-08 16:42 UTC, ivelin commented
@sniperadmin is this PR still active?

2021-05-16 17:32 UTC, ivelin commented
Closing due to inactivity for over 30 days.

2021-05-16 17:32 UTC, closed without merging