fix: made visibility icon responsive to small resolutions
ambianic/ambianic-ui pull request #514
Opened 2021-02-04 19:55 UTC by vickywane

This resolves: #513 

This PR contains fixes made to make the `peerID Visibility Icon` responsive to smaller resolutions.
The applied solution is to make proper use of `media queries` for the input container and also divide the PeerID's length by 2 when hidden. This ensures it doesn't overflow the appropriate space.

**Note:** The `peerID` length is only divided when hidden. The full value is revealed when visible. 

See attached screenshots:

![media-queries](https://user-images.githubusercontent.com/29664439/106947847-3bd4f980-672b-11eb-8ede-0f7cf31e024b.png)

2021-02-04 20:05 UTC, vickywane commented
For some unexplainable reason, the lighthouse check is exiting with an `Error: Timeout reached: Unable to connect to https://deploy-preview-514--ambianic-pwa-dist.netlify.app` error after logging `URL unavailable`. 

Is there a way to re-trigger the check with pushing again ( I don't have any new thing to push).

2021-02-05 08:04 UTC, ivelin commented
@vickywane Lighthouse PWA CI / build check fails.

2021-02-05 20:35 UTC, ivelin requested changes
This works at the moment, but the value dividing doesn't feel right. The size of the text field should be controlled by the screen size and not by the length of the text is contains.

What if sometime down the road we have to switch to public keys for peer ID value, which can be 500+ characters long?

Please look closer at the vuetify responsive attributes that ensure components fit well. The solution you found for the buttons going outside mobile screen boundaries was great.

Let's avoid custom responsive code with hardcoded pixel values that may conflict with the vuetify built-in component layout algorithm.

See vuetify grids: https://vuetifyjs.com/en/components/grids/

2021-02-06 23:54 UTC, ivelin requested changes
One issue and one question:

1. The left alignment of the ID text seems off on screens bigger than iphone 5. Have you tested responsiveness thoroughly before requesting PR review? See screenshots.
2. The placement of the eye icon is space efficient. I like that. However it does not make it obvious that it's an interactive button as opposed to a static icon like the rest of the icons in that column of the screen. The user has to guess which icon does what. May be confused that all icons but one  have no action associated with them. How do we address that with some sort of visual cue that distinguishes a button icon from a static one?

![Screen Shot 2021-02-06 at 5 48 30 PM](https://user-images.githubusercontent.com/2234901/107132379-043d8d00-68a4-11eb-9a76-f54d0d5ac867.png)
![Screen Shot 2021-02-06 at 5 48 37 PM](https://user-images.githubusercontent.com/2234901/107132380-056eba00-68a4-11eb-836e-09f0b816a688.png)
![Screen Shot 2021-02-06 at 5 48 42 PM](https://user-images.githubusercontent.com/2234901/107132381-069fe700-68a4-11eb-98dc-9dfb6416cc8b.png)
![Screen Shot 2021-02-06 at 5 48 52 PM](https://user-images.githubusercontent.com/2234901/107132382-069fe700-68a4-11eb-97dc-258e21145d40.png)
![Screen Shot 2021-02-06 at 5 48 59 PM](https://user-images.githubusercontent.com/2234901/107132383-07387d80-68a4-11eb-8090-86fee27287ef.png)
![Screen Shot 2021-02-06 at 5 49 05 PM](https://user-images.githubusercontent.com/2234901/107132384-07387d80-68a4-11eb-9357-ddda7fed7fb8.png)

2021-02-07 20:47 UTC, ivelin commented
@vickywane lets add responsiveness tests that validate component visibility and layout under various device modalities: mobile (top 10 popular models), tablet, desktop:

Resources:
- https://maxschmitt.me/posts/cypress-testing-mobile-tablet-desktop/
- https://docs.cypress.io/api/commands/viewport.html#Usage
- https://medium.com/flux-it-thoughts/responsive-testing-cypress-72d2be68690b
- https://docs.cypress.io/guides/tooling/visual-testing.html#Functional-vs-visual-testing
- https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Visibility

2021-02-07 22:17 UTC, ivelin requested changes

2021-02-07 22:17 UTC, ivelin commented on src/views/Onboarding.vue
> +              'Hi Blob, please send me an access invitation to your Ambianic Edge Device'
@vickywane  Please change "Blob" to "_____".  Blob may be offensive to some users.

2021-02-07 22:17 UTC, ivelin commented on src/components/shared/ListItem.vue
> +      arr.splice(0, arr.length / 2)
@vickywane Dividing the text length by two is not an optimal solution. The value can be much longer than it is now in the future (e.g. a 500 char public key ), but that should not break the page. 

The good news however is that due to your latest use vuetify layout markup, I think you can just get rid of this `divideIdValue` function and everything should still look fine.

2021-02-08 03:39 UTC, vickywane commented on cypress/integration/ambianic-tests/remote-connection.spec.js
> +    it('Displays elements in smaller viewports', () => {
Sure, this would be taken note of.

2021-02-08 05:44 UTC, ivelin requested changes

2021-02-08 05:44 UTC, ivelin commented on src/views/Onboarding.vue
> +              'Hi Blob, please send me an access invitation to your Ambianic Edge Device'
The same request text appears twice in the same file. One is now using ___ and the other Blob....Is there a better way to handle repetitive literals?

2021-02-08 17:37 UTC, merged

2021-02-08 17:44 UTC, ivelin commented
:tada: This PR is included in version 2.12.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ambianic-ui/v/2.12.2)
- [GitHub release](https://github.com/ambianic/ambianic-ui/releases/tag/v2.12.2)
- `v2.12.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: