feat: implemented usage of exisitng remote ID
ambianic/ambianic-ui pull request #728
Opened 2021-09-21 16:14 UTC by vickywane

## Purpose
This pull request will close [this issue](https://github.com/ambianic/ambianic-ui/issues/725).

## Approach
Work done within this pull request modifies the installation steps within the onboarding page to allow a user enter the remote peer ID of an edge device when onboarding an existing edge device locally.

## Merge Checklist
- [ ]  The code change is tested and works locally.
- [x]  The user and dev documentation is up to date.
- [x]  There is no commented out code in this PR.
- [x]  No lint errors (use flake8)
- [ ]  100% test coverage

2021-09-22 14:55 UTC, vickywane commented
This pull request is fully ready for review. 

The netlify checks failing is due to the absence of a `yarn.lock` file. I removed that since we are sticking to NPM.

2021-09-23 13:27 UTC, ivelin requested changes
There are 6 failing checks. Please go through each and fix.

2021-09-25 15:36 UTC, vickywane commented
@ivelin This pull request is now ready for  review as I have taken care of the DCO check, and added a video to show a locally tested version of the new flow.

2021-09-26 16:12 UTC, ivelin requested changes
@vickywane good flow. Please break up the large convoluted file into maintainable modules and increase test coverage.

2021-09-26 16:12 UTC, ivelin commented on cypress/integration/ambianic-tests/onboarding.spec.js
> -  it('It confirms remote request message and request grant', () => {
@vickywane why did you get rid of the request grant test? It's still a valid scenario we need to cover. Check that the request dialogs show up, etc. Test that the offered request mediums show up as expected: email, message.

2021-09-26 16:12 UTC, ivelin commented on src/views/Onboarding.vue
> +                <div v-if="stepContentName === 'edge-installation-question'">
@vickywane this file has become too large. Nearly 1,000 lines. It's nearly impossible to follow the logic and the interdependency between states. I spent a lot of time resolving issues with the Install PWA step, which was broken and left the use with the impression that the app was installed, when in reality it was just eating silently browser exceptions. The code in this one file became too convoluted. Please break it up into ~200 LOC files that can be independently tested.

2021-10-08 18:20 UTC, ivelin requested changes
@vickywane Nice design! Please see comments on adding unit tests, namespacing and some cleanup.

2021-10-09 10:25 UTC, vickywane commented
> Entering direct remote peer ID gets stuck. The error message in the log that "PeerJS: Error ID... is taken" indicates that we are causing competing instances of PeerJS to establish remote connection. Need to debug what causes this. We should make sure that the app uses exactly one active peerjs instance.

I think this issue is a known problem similar to [bug report](https://github.com/ambianic/ambianic-ui/issues/710) and is being worked upon within this [pull request](https://github.com/ambianic/ambianic-ui/pull/727).

2021-10-09 10:33 UTC, vickywane commented
> 2. When a remote peer ID is entered, the UI shows some activity (see dev console logs) but does not result in the expected connection. After click on Cancel, and then submitting the remote Peer ID again, then the connection happens as expected.

This works normally when i try to reproduce this.

Can you please show a recording for this? 
Also, could this be a case of the peer-network fluctuating?

2021-10-10 18:21 UTC, ivelin requested changes
@vickywane looking good. Almost there.

Please check the two unresolved conversation
![Screen Shot 2021-10-10 at 1 21 32 PM](https://user-images.githubusercontent.com/2234901/136708448-b2bd05e1-a6f5-41dd-a9e0-f55145413e89.png)
s.

2021-10-10 20:36 UTC, vickywane commented
> Please check the two unresolved conversation

I have responded to the comment on cypress test. 

I'm working on the Vuex namespace comment.

2021-10-11 19:30 UTC, vickywane commented
@ivelin This [GitHub issue](https://github.com/ambianic/ambianic-ui/issues/755) has been created to track the work done to introduce namespaces within the PWA.

2021-10-12 16:30 UTC, ivelin requested changes
@vickywane see comments related to use of local storage.

2021-10-15 15:58 UTC, ivelin requested changes
Still not ready. Please Do Not submit another hasty PR. Test thoroughly manually and with unit tests before requesting review again.

2021-10-19 14:06 UTC, ivelin requested changes
Almost there. 
The label "Already have a Remote Peer ID" is barely visible on my screen. See screenshot. Let's use a default color instead of a custom color that is not tested on all typical user screens.

See the other comment about still inconsistent variable naming.

![Screen Shot 2021-10-19 at 9 03 46 AM](https://user-images.githubusercontent.com/2234901/137926495-6e4dbc77-22b9-4268-932b-7b7efb070baf.png)

2021-10-19 18:25 UTC, ivelin requested changes
address open comments

2021-10-19 20:07 UTC, ivelin requested changes
"Already have a valid Peer ID" label is still barely visible. See screenshot

![Screen Shot 2021-10-19 at 3 05 19 PM](https://user-images.githubusercontent.com/2234901/137982787-fc5d8179-ed4f-4e48-91f7-0ac84b5a480e.png)
.

2021-10-28 16:02 UTC, ivelin requested changes
First of all, CI checks are failing.
Second, I asked for two other reviewers to test and approve the UX thoroughly before submitting back to me.
Thank you.

2021-11-03 17:30 UTC, ivelin commented
This is now addressed via #757

2021-11-03 17:30 UTC, closed without merging